'use strict';

module.exports = function(types) {
    types.registerDeviceType('light')
        .requireCapability('state', 'power')
        .when('dimmable')
            .action('brightness')
                .argument('percentage:change', true, 'Brightness to set')
                .argument('duration', true, 'Transition time for brightness change')
                .returns('percentage', 'The brightness of this light')
                .done()
            .action('setBrightness')
                .argument('percentage', 'Brightness Percentage')
                .argument('duration', true, 'Transition time for brightness change')
                .returns('percentage', 'The brightness that was actually set')
                .done()
            .action('increaseBrightness')
                .argument('percentage', 'Percentage to increase')
                .argument('duration', true, 'Transition time for brightness change')
                .returns('percentage', 'The brightness that was actually set')
                .done()
            .action('decreaseBrightness')
                .argument('percentage', 'Percentage to decrease')
                .argument('duration', true, 'Transition time for brightness change')
                .returns('percentage', 'The brightness that was actually set')
                .done()
            .done()
        .when('color')
            .action('color')
                .argument('color', true, 'Color to set')
                .argument('duration', true, 'Transition time for color change')
                .returns('color', 'The color of this light')
                .done()
            .action('setColor')
                .argument('color', 'The new color of the light')
                .argument('duration', true, 'Transition time for color change')
                .returns('color', 'The color that was actually set')
                .done()
            .done()
        .when('color:temperature')
            .done()
        .when('color:full')
            .done()
        .done();
};
